# Generated by Django 5.1.4 on 2024-12-13 04:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedán'), ('SUV', 'SUV'), ('Wagon', 'Wagon'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2023)])),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='djangoapp.carmake')),
            ],
        ),
    ]
